# Application Configuration
# This file contains NON-SENSITIVE settings only
# Do not add credentials, tokens, or passwords here

databricks:
  # Databricks workspace host (without https://)
  host: "e2-demo-field-eng.cloud.databricks.com"

  # Serving endpoint name
  endpoint_name: "mas-1ab024e9-endpoint"

database:
  # Database host (leave empty to disable conversation history)
  name: "osc-delete-nov1"
  host: "instance-4401e5e2-c276-4302-8519-e9c3226ef66b.database.cloud.databricks.com"
  port: 5432
  database: "databricks_postgres"
app:
  # Application title
  title: "OSC Market Intelligence"

  # Page layout: "wide" or "centered"
  layout: "wide"

  # Enable async query support
  async_queries_enabled: true
