# Application Configuration
# This file contains NON-SENSITIVE settings only
# Do not add credentials, tokens, or passwords here

databricks:
  # Databricks workspace host (without https://)
  host: "e2-demo-field-eng.cloud.databricks.com"

  # Serving endpoint name
  endpoint_name: "mas-1ab024e9-endpoint"

database:
  # Lakebase instance name (leave empty to disable conversation history)
  instance_name: "osc-delete-nov1"

  # Database name within the Lakebase instance
  database_name: "databricks_postgres"
app:
  # Application title
  title: "OSC Market Intelligence"

  # Page layout: "wide" or "centered"
  layout: "wide"

  # Enable async query support
  async_queries_enabled: true
