# Application Configuration
# This file contains NON-SENSITIVE settings only
# Do not add credentials, tokens, or passwords here

databricks:
  # Databricks workspace host (without https://)
  host: "e2-demo-field-eng.cloud.databricks.com"

  # Serving endpoint name
  endpoint_name: "mas-1ab024e9-endpoint"

  # MLflow experiment name for tracing (full path)
  # This is where the agent logs its traces
  experiment_name: "/Users/jag.jasani@databricks.com/mas-1ab024e9-dev-experiment"

database:
  # Lakebase instance name (leave empty to disable conversation history)
  instance_name: "osc-delete-nov1"

  # Database name within the Lakebase instance
  database_name: "databricks_postgres"

  # Service principal ID for database authentication
  # This is the UUID of the app's service principal (from "role does not exist" error)
  # Required for Databricks Apps deployment - leave empty for local development
  service_principal_id: "2ab35418-2e68-42a1-8911-957f8ea7b1a0"
app:
  # Application title
  title: "OSC Market Intelligence"

  # Page layout: "wide" or "centered"
  layout: "wide"
