artifact_location: /Users/scott.mckean/Repos/market_intelligence_app/databricks/aws/0
creation_time: 1761668826167
experiment_id: '0'
last_update_time: 1761668826167
lifecycle_stage: active
name: Default
